# Generated by Django 3.2.7 on 2021-10-04 03:40

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0003_auto_20210929_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='category_section',
            field=models.ForeignKey(blank=True, help_text='Featured section for the homepage. Will display all themes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Theme section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='category_section_intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='category_section_title',
            field=models.CharField(blank=True, help_text='Title to display above the theme section', max_length=255, null=True),
        ),
    ]
