# Generated by Django 3.2.7 on 2021-10-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0004_auto_20211004_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='category_section',
            field=models.ForeignKey(blank=True, help_text='Featured section for the homepage. Will display all themes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Category section'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='category_section_title',
            field=models.CharField(blank=True, help_text='Title to display above the category section', max_length=255, null=True),
        ),
    ]
